# Generated by Django 2.0.7 on 2021-05-17 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('customuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneNumber', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderCode', models.CharField(max_length=15)),
                ('title', models.FileField(upload_to='documents')),
                ('print_type', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two')])),
                ('bind_type', models.PositiveSmallIntegerField(choices=[(1, 'claims'), (2, 'soft'), (3, 'spiral')])),
                ('number_of_copies', models.PositiveIntegerField()),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'color'), (2, 'white-black')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='printStudioApp.CustomUser')),
            ],
        ),
    ]
