# Generated by Django 3.2.3 on 2021-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printStudioApp', '0004_auto_20210529_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusform',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
